baseURL = 'https://xy-iii.github.io'
languageCode = 'en-us'
title = 'ğ’©ğ‘’ğ“‹ğ‘’ğ“‡ ğ“€ğ“ƒğ‘œğ“Œğ“ˆ ğ’·ğ‘’ğ“ˆğ“‰'
theme = 'xyiii'
publishDir = 'docs'
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false
